import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Phoenix Education Hub",
  description: "Generated by create next app",
  themeColor: "#1e3a8a",
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
  },
};

// Android Chrome & other browsers use this to tint the top bar.
// iOS Safari only applies this when installed to Home Screen.
export const viewport: Viewport = {
  // Tailwind blue-900
  themeColor: "#1e3a8a",
  viewportFit: "cover",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body
        className="min-h-full flex flex-col"
        style={{ paddingTop: "env(safe-area-inset-top)" }}
      >
        <div
          aria-hidden
          className="fixed left-0 right-0 top-0 z-50 bg-linear-to-br from-blue-950 via-blue-900 to-blue-800"
          style={{ height: "env(safe-area-inset-top)" }}
        />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
